# Generated by Django 5.2.5 on 2025-08-16 13:22

import django.db.models.deletion
import django.utils.timezone
import rooms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(default=rooms.models.short_id, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('running', 'Running'), ('ended', 'Ended')], default='lobby', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
