# Generated by Django 5.2.5 on 2025-08-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default=1, help_text='방 이름', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, help_text='비밀번호', max_length=128, null=True),
        ),
    ]
